"""create Scanity ERD tables

Revision ID: ea1c0b057c6b
Revises: 
Create Date: 2026-09-07 19:12:22.135158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1c0b057c6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergy_types',
    sa.Column('allergy_type_id', sa.UUID(), nullable=False),
    sa.Column('allergen_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('allergy_type_id')
    )
    op.create_table('health_condition_types',
    sa.Column('condition_type_id', sa.UUID(), nullable=False),
    sa.Column('condition_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('condition_type_id')
    )
    op.create_table('ingredients',
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=100), nullable=True),
    sa.Column('common_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_allergen', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('nutrition_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=True),
    sa.Column('nutrient', sa.String(length=255), nullable=True),
    sa.Column('limit_value', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('barcode', sa.String(length=20), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('brand', sa.String(length=25), nullable=True),
    sa.Column('category', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=35), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('health_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('product_ingredients',
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], )
    )
    op.create_table('product_nutrition_flags',
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['nutrition_rules.rule_id'], )
    )
    op.create_table('scan_histories',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('scan_date', sa.DateTime(), nullable=True),
    sa.Column('scan_method', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_table('user_allergies',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('allergy_type_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['allergy_type_id'], ['allergy_types.allergy_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], )
    )
    op.create_table('user_health_conditions',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('condition_type_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['condition_type_id'], ['health_condition_types.condition_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_health_conditions')
    op.drop_table('user_allergies')
    op.drop_table('scan_histories')
    op.drop_table('product_nutrition_flags')
    op.drop_table('product_ingredients')
    op.drop_table('health_profiles')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('nutrition_rules')
    op.drop_table('ingredients')
    op.drop_table('health_condition_types')
    op.drop_table('allergy_types')
    # ### end Alembic commands ###
